### ISSUE TITLE
 “Agreeing to terms and privacy policy is required ” issue while I register account

### ISSUE THREAD

**Issue by laohixdxm** [openhab/openhab-cloud#118]
1  “Agreeing to terms and privacy policy is required ” message pop up while I click "register" button.
![image](https://user-images.githubusercontent.com/6562792/28983025-a9031340-790c-11e7-9c40-0d05d703e3e6.png)

supposedly, there is a checkbox. But I can NOT see that as in myopenhab.org.
![image](https://user-images.githubusercontent.com/6562792/28982662-7edd0180-790b-11e7-8d1f-3b732de06c47.png)

2 The first issue to have this issue,
commit 181f04781b42cd82870c2988ec753132f951e77a
Author: Florian <florian.schmidt.welzow@t-online.de>
Date:   Fri Jul 21 18:00:51 2017 +0200

    Update express 3.x to express 4.x (#109)

3 I also post same issue in forum.
https://community.openhab.org/t/agreeing-to-terms-and-privacy-policy-is-required-issue/32711

**Comment by marziman** [comment]
@laohixdxm ,

thank you very much. That was really introduced with that commit and I didnt expect that @FlorianSW did logical changes there. I guess this was unintentionally and we need to test more carefully at least the basic functionalities. Hopefully we will soon have some CI in place to find this small things. I took my a little time to find it, since it was some time ago.

Should be fixed with https://github.com/openhab/openhab-cloud/pull/120
Can you please re-test it and let me know? 

Thx & BR Mehmet

**Comment by marziman** [comment]
@laohixdxm , small hint: Please try to not show your credentials..also UUID etc. for Security & Privacy reasons.

**Comment by JeetTechie** [comment]
@marziman thanks! working perfect...

**Comment by laohixdxm** [comment]
@marziman thanks. I will generate new uuid/secret.

**Comment by FlorianSW** [comment]
@marziman We could close this issue, now, right? :)

**Comment by marziman** [comment]
Yes!
