### ISSUE TITLE
login (e-mail address) should not be case sensitive

### ISSUE THREAD

**Issue by kaikreuzer** [openhab/openhab-cloud#19]
There is a huge number of users that get the case wrong when trying to log in with their e-mail address.

As email addresses aren't case sensitive, it imho does not make sense to treat them as case sensitive on the login screen either - this change would for sure reduce the support efforts.

**Comment by digitaldan** [comment]
Just for some context, this was hard to fix on our previous environment due to the older version of mongo we were running.  Since moving to updated infrastructure for myopenhab.org services we are on the latest version of mongo which should help solving this with along with a minimal amount of code changes.

**Comment by marziman** [comment]
This is fixed by ps://github.com/openhab/openhab-cloud/pull/32
