### ISSUE TITLE
Proxy for /gpstracker

### ISSUE THREAD

**Issue by DerOetzi** [openhab/openhab-cloud#231]
For easy usage of the new gpstracker binding with user-authentication /gpstracker/* should be proxied by openhab-cloud.

**Comment by kaikreuzer** [comment]
It is. What's your issue?

**Comment by zolakk** [comment]
I was trying this yesterday and was getting a 404 (in browser) and 403 (in owntracks) on my self hosted instance at https://myopenhab.mydomain.com/gpstracker/owntracks using a fresh pull from this repo.

**Comment by kaikreuzer** [comment]
Hm, ok - I was only using myopenhab.org, where this actually works when using home.myopenhab.org - maybe there's a difference for the self-hosted version, @digitaldan or @marziman might better be able to answer that.

**Comment by zolakk** [comment]
It turns out I was on the wrong track after seeing issue #177 where it was mentioned that the host name has to be "home" for basic authentication. I rolled back the change I mentioned earlier and set up a cname on my DNS for home.openhab.mydomain.com, pointing to openhab.mydomain.com and got another cert for the new home.openhab virtual host. I then copied the original nginx config file and just changed the server name and cert name entries to point to home.openhab and now everything is working. OwnTracks posts successfully to https://home.openhab.mydomain.com and my existing alexa skill still works communicating to https://openhab.mydomain.com. Just gotta figure out how to get the "Click here to access your dashboard" link to point to home.openhab like myopenhab does and I'll be all set

**Comment by DerOetzi** [comment]
Why is there a difference between /rest, /basicui, /paperui and /gpstracker urls? the first three work fine with https://smarthome.mydomain.com. Why do I need to use for home.-subdomain for gpstracker?

I have a wildcard cert for *.mydomain.com but not for *.*.mydomain.com and I don't want to buy another for this. 

I have done two changes locally to make it work without the need of home

app.js

`
app.use(function (req, res, next) {
    var csrf = csurf();
    // Check if url needs csrf, remote connections and REST connections are excluded from CSRF
    if (!req.path.match('/rest*') && !req.path.match('/oauth2/token') && !req.path.match('/ifttt/*')
        && !req.path.match('/remote/*') && !req.path.match('/gpstracker/*'))
        csrf(req, res, next);
    else
        next();
});
`

routes/index.js:

`
    app.all('/habpanel/*', this.ensureRestAuthenticated, this.preassembleBody, this.setOpenhab, this.ensureServer, this.proxyRouteOpenhab.bind(this));
    app.all('/gpstracker/*', this.ensureRestAuthenticated, this.preassembleBody, this.setOpenhab, this.ensureServer, this.proxyRouteOpenhab.bind(this));
`
Are there any disadvantages with this approach?

**Comment by alackmann** [comment]
@DerOetzi will you pull request your change/fix? I have this issue also and would prefer not to mess about with additional CNAMEs

**Comment by alackmann** [comment]
I've tested the above PR on my own docker based install/build and OwnTracks is now functional and correctly reporting via my self hosted OpenHAB Cloud. Previously it was broken. As the route is authenticated - I don't think CSRF check is critical.

**Comment by digitaldan** [comment]
Closing this as the correct solution is to use the proxy domain "home" for endpoints.  FYI, the only reason we have for keeping  hardcoded proxy paths around in the code (like /rest or /icons) is for legacy puposes, mainly oh1/oh2/  with oh3 the default UI won't work without using the home domain.
