### ISSUE TITLE
unable to access OH3 dashboard

### ISSUE THREAD

**Issue by candiesdoodle** [openhab/openhab-cloud#313]
Hi.
I understand that OH3 is still in snapshot.. but still wanted to post this regarding my own OH cloud deployment.

Where it says "Your openHAB is online. Click here to access your openHAB's dashboard"

**from myopenhab.org:**
i can access my local OH3 dashboard - i.e., there is a link to "home.myopenhab.org" which correctly connects and accesses by local OH server.
Insepctig the page:
`Your openHAB is online. <a href="https://home.myopenhab.org:443/">Click here to access your openHAB's dashboard</a>`

**from mydomain.com:**
When i deploy my own OH Cloud instance, i cant access the dashboard. Even though the connection is established and i can pull up https://mydomain.com/rest/items ... but the home page still links to "https://mydomain.com". Clicking it keeps opening up the same page and does not access the local OH3.
Inspecting the page:
`Your openHAB is online. <a href="https://mydomain.com:443/">Click here to access your openHAB's dashboard</a>`

**from mydomain.com with OH2:**
No changes to OH cloud. Local OH moved to OH2. Successfully able to access the dashboard. The link is a OH2 specific link.
Inspecting the page:
`Your openHAB is online. <a href="https://mydomain.com:443/start/index">Click here to access your openHAB's dashboard</a>`

**My config.json file** (relevant part only):

> system": {
>         "host": "mydomain.com",
>         "port": "443",
>         "protocol": "https",
>         "logger" : {
>             "dir": "./logs",
>             "maxFiles" : "7d",
>             "level" : "debug",
>             "morganOption" : "dev"`

I am using the latest code from github.

**Comment by digitaldan** [comment]
oh3 UI uses the root path "/" so you can not proxy that without a separate host that only serves proxy requests.  You will need to setup a new host , even if that is a CNAME to the main one, with the name 'home', which the cloud code will treat as a pure proxy request.  

For example if your OHC host is cloud.mydomain.com you can setup a CNAME of home.cloud.mydomain.com to point to  cloud.mydomain.com, and make sure your nginx or trafik load balancer knows about it with the right certificates.  In your config.json add a new parameter `proxyHost` set to `home.cloud.mydomain.com` so that the link on the main page is directed to this host. 

See https://github.com/openhab/openhab-cloud/blob/master/etc/nginx_openhabcloud-production.conf#L21 for an example of  how the routing works.

**Comment by candiesdoodle** [comment]
Thank you very much. This worked! The `proxyHost` was the key. I'll post a detailed write up. Here is my config.json for reference (the initial part)
````
"system": {
        "host": "openhab.mydomain.com",
        "port": "443",
        "protocol": "https",
        "proxyHost": "home.openhab.mydomain.com",
        "logger" : {
            "dir": "./logs",
            "maxFiles" : "7d",
            "level" : "debug",
            "morganOption" : "dev"
          }
    },
````

**Comment by vshaev** [comment]
Hello,
Sorry, but my knowledge is not enough to apply your recommendations.
Adding "proxyHost": "home.openhab.mydomain.com" to config.json does not solve the problem.
Could you describe all the necessary steps step by step? At least which configuration files to make changes.

**Comment by rlodge** [comment]
@candiesdoodle 

> I'll post a detailed write up. Here is my config.json for reference (the initial part)

Did you ever write something up more detailed than this?  I can get the dashboard link to point to the cname, but when I click on it I get a blank screen and errors like it's trying to load the openhab page again.  I've tried various resources but can't find something definitive about how to make it work (or if it works).
