### ISSUE TITLE
Getting frequently Disconnects and 504 Gateway-Timeout permanently

### ISSUE THREAD

**Issue by helmar74** [openhab/openhab-cloud#36]
Hi,

I've setup a new OH2 Installation and I installed the openhab cloud connector. After setting up connection to myopenhab.org I recognized that I get the following errors in /var/log/openhab2/openhab.log:

2017-02-02 06:56:45.312 [INFO ] [io.openhabcloud.internal.CloudClient] - Disconnected from the openHAB Cloud service (UUID = 9838aa4d-ec6b-44b6-ae07-5c4572300f7d, base URL = http://localhost:8080)
2017-02-02 06:56:46.767 [INFO ] [io.openhabcloud.internal.CloudClient] - Connected to the openHAB Cloud service (UUID = 9838aa4d-ec6b-44b6-ae07-5c4572300f7d, base URL = http://localhost:8080)

The errors occurs frequently, every few minute in the log file.

I also get a 504 Gateway-Timeout, when I try to connect to https://home.myopenhab.org .

I think the 504 error occurs regarding the error messages in openhab.log.

My openhab2 system is shown "Online" in the myopenhab.org Startscreen.

Has anyone an idea what I can do to get a "stable" myopenhab installation.

**Comment by helmar74** [comment]
I found out, that more people are having this issue:
[https://community.openhab.org/t/myopenhab-org-down/21748/11]

**Comment by kobelka** [comment]
I also got the same problem and when I try to log in the webinterface on myopenhab.org I get an 504 Time Out
And at the same time the status.openhab.org says everythings fine....

@digitaldan @kaikreuzer

**Comment by kaikreuzer** [comment]
Note that this issue tracker is not for availability of the myopenhab.org server - it is about bugs in the behavior of the code. I do not actually see a bug report in here.

The availability issues are due to https://github.com/openhab/openhab-cloud/issues/20, which forces us to do a regular reboot. If any of you can help analysing that issue (we need a node.js expert here), please let us know.
