### ISSUE TITLE
myopenhab change uuid and secret after saving old value are shown

### ISSUE THREAD

**Issue by kobelka** [openhab/openhab-cloud#41]
I purged my old openhab version and installed a new one.
So I also have to change the uuid and secret in myopenhab.org.
After I have clicked Update the old values are shown again, also if you browse z.b. to events and back to account the old values are shown. Only if you logout and login again the new values where shown.

**Comment by digitaldan** [comment]
FYI for anyone looking at the code, this is due to our mongoose caching, we update the value correctly but when the page loads again it uses the cached value.  We really don't need to be caching here anyways.

**Comment by FlorianSW** [comment]
This could be fixed with a proper way to invalidate the cache, like I requested here:
https://github.com/Gottox/mongoose-cache/issues/17

Until we've this feature, we probably really don't need to cache these values. Btw.: This is the second time, where the cache seems to break things (the first one was #92). Do we know if it is worse to use mongoose-cache that much?

**Comment by marziman** [comment]
I agree with you and we can remove the caching.

**Comment by PaulSinnema** [comment]
This issue is closed but it still happening to me. Must be something else than the cache then?
