### ISSUE TITLE
Paper UI not working

### ISSUE THREAD

**Issue by kobelka** [openhab/openhab-cloud#66]
Hi, 
I´ve installes an own Openhab Cloud but when I try to open PaperUI the following Error comes up:

```   
Cannot GET /paperui/index.html
```
Regards
Kobelka

**Comment by marziman** [comment]
@kobelka,
there is already a PR to solve this by configuration.
If you use myopenhab.org you should hit:
https://home.myopenhab.org/paperui/index.html
otherwise you need to access via:
https://your-OH-URL:port/paperui/index.html

In your comment it is not clear what you mean diectly. To access from browser, ohcloud ui ..?

**Comment by snoekieboe** [comment]
@marziman, i think we are mixing things up here.. 

The problem we are talking about is not the incorrect URL but PaperUI not working even when the when you are forwarded to the correct URL .

In my case the paper ui logo is grey (ish) and refers to https://openhab.heerle.com/paperui/index.html but when clicking it throws " Cannot GET /paperui/index.html"  as an error.

All other UI's like basic, classic, habmin & habpanel are working just fine.

**Comment by marziman** [comment]
Testing this right now.

**Comment by marziman** [comment]
@snoekieboe,

you re right. I really mixed this up. I am just testing and merging this in.
Sorry and Thanks for your patience..
BR Mehmet

**Comment by marziman** [comment]
Fixed with https://github.com/openhab/openhab-cloud/pull/73

**Comment by snoekieboe** [comment]
Thnx Marziman!!
